# Generated by Django 6.0.7 on 2026-07-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Precision LED systems for every arena.', max_length=500)),
                ('hero_subtitle', models.TextField(default='Professional sports lighting solutions trusted in over 50 countries. From community fields to broadcast-ready stadiums, engineered for performance, built to outlast.')),
                ('hero_background', models.ImageField(blank=True, help_text='Hero background image', upload_to='site/')),
                ('stat_projects', models.CharField(default='500+', max_length=100)),
                ('stat_projects_label', models.CharField(default='Projects', max_length=100)),
                ('stat_countries', models.CharField(default='50+', max_length=100)),
                ('stat_countries_label', models.CharField(default='Countries', max_length=100)),
                ('stat_energy', models.CharField(default='60%', max_length=100)),
                ('stat_energy_label', models.CharField(default='Energy Save', max_length=100)),
                ('stat_support', models.CharField(default='24/7', max_length=100)),
                ('stat_support_label', models.CharField(default='Support', max_length=100)),
                ('about_title', models.CharField(default='Trusted worldwide for a reason.', max_length=500)),
                ('about_text_1', models.TextField(default="Since 2007, SolarOne Vision has focused on the design and manufacture of high power LED Sports lighting systems, LED Roadway infrastructure lighting systems, and LED industrial lighting systems. We bring first-hand knowledge and experience for new and retrofit projects — from small projects requiring a few lights to professional high-level facilities, we've got you covered.")),
                ('about_text_2', models.TextField(default="SolarOne's mission is to deliver innovative outdoor and indoor lighting solutions for recreational, high school, college, and semi-professional sports venues, airports, seaports, and other industrial facilities. We protect the environment, reduce energy consumption, deliver satisfying and inspiring lighting experiences, and add value to people's vision of life.")),
                ('about_stat_years', models.CharField(default='18+', max_length=100)),
                ('about_stat_years_label', models.CharField(default='Years Experience', max_length=100)),
                ('about_stat_projects', models.CharField(default='500+', max_length=100)),
                ('about_stat_projects_label', models.CharField(default='Projects Delivered', max_length=100)),
                ('about_stat_countries', models.CharField(default='50+', max_length=100)),
                ('about_stat_countries_label', models.CharField(default='Countries Served', max_length=100)),
                ('about_stat_clients', models.CharField(default='1000+', max_length=100)),
                ('about_stat_clients_label', models.CharField(default='Happy Clients', max_length=100)),
                ('products_title', models.CharField(default='Our Products', max_length=500)),
                ('products_subtitle', models.TextField(default='From compact modular luminaires to stadium-grade high bay systems. Precision optics, modular architecture, and field-proven reliability across every product line.')),
                ('projects_title', models.CharField(default='Featured Projects', max_length=500)),
                ('projects_subtitle', models.TextField(default='Real installations across five continents. From Olympic training centers to community football pitches, our luminaires deliver reliable performance under the toughest conditions.')),
                ('contact_title', models.CharField(default='Get in Touch', max_length=500)),
                ('contact_subtitle', models.TextField(default='Have a project in mind? Send us the details and our engineering team will respond with a full photometric proposal within 48 hours.')),
                ('contact_email', models.EmailField(default='sales@solarone.com', max_length=254)),
                ('contact_phone_1', models.CharField(default='+86 400 0000 0000', max_length=200)),
                ('contact_phone_2', models.CharField(default='+86 130 0000 0000', max_length=200)),
                ('contact_whatsapp', models.CharField(default='+86 130 0000 0000', max_length=200)),
                ('contact_address', models.CharField(default='Beijing, China', max_length=500)),
                ('social_facebook', models.URLField(blank=True, default='https://facebook.com')),
                ('social_instagram', models.URLField(blank=True, default='https://instagram.com')),
                ('social_youtube', models.URLField(blank=True, default='https://youtube.com')),
                ('social_tiktok', models.URLField(blank=True, default='https://tiktok.com')),
                ('social_linkedin', models.URLField(blank=True, default='')),
                ('footer_description', models.TextField(default='Professional LED lighting systems for sports, industrial, and infrastructure applications. Engineered in Beijing since 2007, trusted in 50+ countries worldwide.')),
                ('brand_name', models.CharField(default='SolarOne', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Brand logo', upload_to='site/')),
                ('meta_title', models.CharField(default='SolarOne — Precision LED Lighting Systems', max_length=200)),
                ('meta_description', models.TextField(default='Professional LED sports lighting, high bay, and modular luminaire solutions. Engineered in Beijing since 2007, trusted in 50+ countries worldwide.')),
                ('og_image', models.ImageField(blank=True, help_text='Social sharing preview image', upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
