# Generated by Django 6.0.7 on 2026-07-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_siteconfig_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('unique_visits', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('path', models.CharField(blank=True, default='/', max_length=500)),
                ('referrer', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('country', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('city', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('is_unique', models.BooleanField(default=True, help_text='First visit from this IP today')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitor Records',
                'ordering': ['-visited_at'],
            },
        ),
    ]
