# Generated by Django 6.0.7 on 2026-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_dailystats_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='accent_color',
            field=models.CharField(default='#0088FF', help_text='Primary accent color, e.g. #0088FF, #FF6B00', max_length=20, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_family_body',
            field=models.CharField(default="'Inter', 'Helvetica Neue', Arial, sans-serif", help_text="CSS font-family value, e.g. 'Inter', sans-serif", max_length=200, verbose_name='Body Font Family'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_family_heading',
            field=models.CharField(default="'Inter', 'Helvetica Neue', Arial, sans-serif", help_text='CSS font-family value for headings', max_length=200, verbose_name='Heading Font Family'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_size_base',
            field=models.CharField(default='16px', help_text='Root font size, e.g. 16px, 18px', max_length=10, verbose_name='Base Font Size'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_size_body',
            field=models.CharField(default='1.05rem', help_text='Paragraph text size, e.g. 1.05rem, 1.1rem', max_length=10, verbose_name='Body Text Font Size'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_size_card_desc',
            field=models.CharField(default='0.95rem', help_text='Product/Project card description size', max_length=10, verbose_name='Card Description Font Size'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_size_card_title',
            field=models.CharField(default='1.25rem', help_text='Product/Project card title size', max_length=10, verbose_name='Card Title Font Size'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_size_hero_subtitle',
            field=models.CharField(default='1.15rem', help_text='Hero subtitle size, e.g. 1.15rem, 1.25rem', max_length=10, verbose_name='Hero Subtitle Font Size'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_size_hero_title',
            field=models.CharField(default='3.5rem', help_text='Hero heading size, e.g. 3.5rem, 4rem', max_length=10, verbose_name='Hero Title Font Size'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_size_nav',
            field=models.CharField(default='17px', help_text='Nav link font size, e.g. 15px, 17px, 18px', max_length=10, verbose_name='Navigation Font Size'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_size_section_title',
            field=models.CharField(default='2.25rem', help_text='Section headings size, e.g. 2.25rem, 2.5rem', max_length=10, verbose_name='Section Title Font Size'),
        ),
    ]
