# Generated by Django 5.2.16 on 2026-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_siteconfig_accent_color_siteconfig_font_family_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_phone_1',
            field=models.CharField(default='+8613910887405', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_phone_2',
            field=models.CharField(default='+8613910887405', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_whatsapp',
            field=models.CharField(default='+86 13910887405', max_length=200),
        ),
    ]
