# Generated by Django 5.2.16 on 2026-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_product_translations_project_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL_FIELD', 'Football Field'), ('SOCCER_FIELD', 'Soccer Field'), ('BASEBALL_FIELD', 'Baseball Field'), ('TENNIS_COURTS', 'Tennis Courts'), ('BASKETBALL', 'Basketball'), ('VOLLEYBALL', 'Volleyball'), ('TRACK_FIELD', 'Track and Field'), ('MULTI_SPORT', 'Multi-Sport Arena'), ('STADIUM', 'Stadium'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='venue_type',
            field=models.CharField(choices=[('OUTDOOR', 'Outdoor'), ('INDOOR', 'Indoor')], default='OUTDOOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FLOODLIGHT', 'Flood Lighting'), ('HIGH_BAY', 'High Bay'), ('STREET_LIGHTING', 'Street Lighting'), ('MODULAR', 'Modular'), ('OTHER', 'Other')], max_length=100),
        ),
    ]
