# Generated by Django 6.0.7 on 2026-07-30 10:50

from django.db import migrations


def update_hero_text(apps, schema_editor):
    """Update existing SiteConfig records with new hero title/subtitle."""
    SiteConfig = apps.get_model('pages', 'SiteConfig')
    SiteConfig.objects.filter(
        hero_title='Precision LED systems for every arena.'
    ).update(
        hero_title='The Next Generation Lighting Systems For Every Area',
        hero_subtitle='Professional SolarOne sports lighting solutions trusted in over 50 countries. From community fields to broadcast-ready stadiums, engineered for performance, built to outlast.',
    )


def reverse_update(apps, schema_editor):
    """Reverse migration — restore old text (best-effort)."""
    SiteConfig = apps.get_model('pages', 'SiteConfig')
    SiteConfig.objects.filter(
        hero_title='The Next Generation Lighting Systems For Every Area'
    ).update(
        hero_title='Precision LED systems for every arena.',
        hero_subtitle='Professional sports lighting solutions trusted in over 50 countries. From community fields to broadcast-ready stadiums, engineered for performance, built to outlast.',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_project_sport_type_project_venue_type_and_more'),
    ]

    operations = [
        migrations.RunPython(update_hero_text, reverse_update),
    ]
