# Generated by Django 6.0.7 on 2026-08-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_update_hero_title_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AddField(
            model_name='product',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='产品页顶部 banner。建议 1920×442 像素（最小 1200×280）。', upload_to='products/banners/'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='用于子系列（如 FL1M 属于 M Series）。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.product', verbose_name='父级系列'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AREA_SITE', 'Area and Site'), ('SPORTS_LIGHTING', 'Sports Lighting System'), ('FLOODLIGHT', 'Flood Lighting'), ('HIGHBAY_LOWBAY', 'Highbay & Low Bay'), ('ROADWAY', 'Roadway'), ('ACCESSORY', 'Accessory'), ('MODULAR', 'Modular'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='产品卡片/详情主图。建议 1280×720 像素（16:9，最小 640×360）。', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='项目卡片封面图。建议 1280×720 像素（16:9，最小 640×360）。', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL_FIELD', 'Football Field'), ('SOCCER_FIELD', 'Soccer Field'), ('BASEBALL_FIELD', 'Baseball Field'), ('TENNIS_COURTS', 'Tennis Courts'), ('BASKETBALL', 'Basketball'), ('VOLLEYBALL', 'Volleyball'), ('TRACK_FIELD', 'Track and Field'), ('MULTI_SPORT', 'Multi-Sport Arena'), ('AIRPORT', 'Airport'), ('SEAPORT', 'Seaport'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='venue_type',
            field=models.CharField(choices=[('OUTDOOR', 'Outdoor'), ('INDOOR', 'Indoor'), ('INFRASTRUCTURE', 'Infrastructure')], default='OUTDOOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_subtitle',
            field=models.TextField(default='Professional SolarOne sports lighting solutions trusted in over 50 countries. From community fields to broadcast-ready stadiums, engineered for performance, built to outlast.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(default='The Next Generation Lighting Systems For Every Area', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_energy',
            field=models.CharField(default='50%+', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_support',
            field=models.CharField(default='5+', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_support_label',
            field=models.CharField(default='warranty', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='轮播图。建议 1280×720 像素（16:9，最小 640×360）。', upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt 文本')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品轮播图',
                'verbose_name_plural': '产品轮播图',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='项目详情轮播图。建议 1280×720 像素（16:9，最小 640×360）。', upload_to='projects/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt 文本')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目轮播图',
                'verbose_name_plural': '项目轮播图',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
