# Generated by Django 6.0.7 on 2026-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_product_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension_image',
            field=models.ImageField(blank=True, help_text='产品尺寸图。建议 1920×1080 像素（16:9，最小 960×540），会在详情页规格下方单独展示。', upload_to='products/dimensions/'),
        ),
    ]
