# Generated by Django 6.0.7 on 2026-08-03 04:50

from django.db import migrations, models


def migrate_legacy_specs(apps, schema_editor):
    """Copy legacy power/efficacy/output/beam_angle/protection fields into the new specs JSON."""
    Product = apps.get_model('pages', 'Product')
    legacy_map = [
        ('power', 'Power'),
        ('efficacy', 'Efficacy'),
        ('output', 'Output'),
        ('beam_angle', 'Beam Angle'),
        ('protection', 'Protection'),
    ]
    for product in Product.objects.all():
        specs = []
        for field, label in legacy_map:
            value = getattr(product, field, '') or ''
            if value.strip():
                specs.append({'label': label, 'value': value.strip()})
        if specs:
            product.specs = specs
            product.save(update_fields=['specs'])


def reverse_migrate_legacy_specs(apps, schema_editor):
    """No-op reverse migration — legacy fields are kept intact."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_product_dimension_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=list, help_text='产品参数，最多 6 组。格式：[{"label": "Power", "value": "80W"}, ...]。页面默认 2 个一排，共 3 排。', verbose_name='Product Specs'),
        ),
        migrations.RunPython(migrate_legacy_specs, reverse_migrate_legacy_specs),
    ]
