# Generated by Django 6.0.7 on 2026-08-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beam_angle_image',
            field=models.ImageField(blank=True, help_text='配光曲线/光束角示意图。建议 1920×1080 像素（16:9，最小 960×540），会在尺寸图上方展示。', upload_to='products/beam_angles/'),
        ),
    ]
