# Generated by Django 6.0.7 on 2026-08-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_product_beam_angle_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Reference image', 'verbose_name_plural': 'Reference images'},
        ),
        migrations.AddField(
            model_name='product',
            name='energy_data',
            field=models.JSONField(blank=True, default=list, help_text='产品能效参数表，用于详情页 ENERGY AND PERFORMANCE DATA 表格。格式：[{"label": "Series Name", "value": "FL4M-320W"}, ...]。label 为参数名称，value 为参数值。不填或留空数组则不显示该行。', verbose_name='Energy & Performance Data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Reference card cover image. Recommended 1280×720 px (16:9, min 640×360).', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Reference detail carousel image. Recommended 1280×720 px (16:9, min 640×360).', upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.project', verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='projects_title',
            field=models.CharField(default='Featured References', max_length=500),
        ),
    ]
