# Generated by Django 6.0.7 on 2026-08-07 02:10

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_project_options_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Optional PDF document for download (e.g. project case study, specification sheet).', upload_to=pages.models.project_pdf_upload_path),
        ),
    ]
