# Generated by Django 6.0.7 on 2026-08-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_project_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_static',
            field=models.CharField(blank=True, help_text='Static PDF path relative to /static/ (e.g. "files/project-case-study.pdf"). Used as persistent fallback on Vercel where uploaded files are ephemeral.', max_length=255),
        ),
    ]
