# Generated by Django 6.1 on 2026-08-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_project_pdf_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text='示例：FL4M-320W-30K-S', max_length=200, verbose_name='Model Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='ordering_info',
            field=models.JSONField(blank=True, default=list, help_text='订购信息表格，9 列，每列支持多行（换行分隔）。格式：["Series Value", "Power Value", "CCT Value", "Voltage Value", "Beam Angle Value", "Color Value", "Controls Value", "Bracket Value", "Driver Location Value"]', verbose_name='Ordering Information'),
        ),
    ]
