# Generated by Django 6.0.7 on 2026-08-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_product_ordering_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Project image', 'verbose_name_plural': 'Project images'},
        ),
        migrations.AddField(
            model_name='product',
            name='cert_image',
            field=models.ImageField(blank=True, help_text='产品认证标识图（如 UL、DLC、CE、IP66 等）。展示在规格下方。留空则使用通用默认认证图。建议 1200×200 像素（横向长条形）。', upload_to='products/certs/', verbose_name='Certification Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='beam_angle_image',
            field=models.ImageField(blank=True, help_text='配光曲线/光束角示意图。建议 1920×540 像素（约 3.56:1 长条形，最小 960×270），会在尺寸图上方展示。', upload_to='products/beam_angles/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_image',
            field=models.ImageField(blank=True, help_text='产品尺寸图。建议 1920×800 像素（2.4:1 长条形，最小 960×400），会在详情页规格下方单独展示。', upload_to='products/dimensions/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_data',
            field=models.JSONField(blank=True, default=[{'label': 'Series Name', 'value': 'FL1M-80W'}, {'label': 'Lumen Output', 'value': '>10,400lm'}, {'label': 'System Wattage', 'value': '80W'}, {'label': 'CRI', 'value': '70-95'}, {'label': 'Color temperature', 'value': '3000K-3500K、4000K-4500k、5500K-5700K'}, {'label': 'Input Voltage (High Voltage)', 'value': '347-480VAC'}, {'label': 'Input Voltage (Low Voltage)', 'value': '110-277VAC'}, {'label': 'L70 Hours', 'value': '>100,000 at 25°C'}, {'label': 'Operating Temperature Range', 'value': '-40°C to 55°C'}, {'label': 'Surge (Common Mode / Differential Mode)', 'value': '10kV'}, {'label': 'IP Rating', 'value': 'IP66'}, {'label': 'Effective Projected Area (EPA) at 90°', 'value': '0.26 (sq. ft.)'}, {'label': 'L" X W" X H"', 'value': '217*234*136mm'}, {'label': 'Approximate Weight', 'value': '2.3 kgs( 5.2 lbs)'}, {'label': 'Material', 'value': 'Aluminum / Glass'}, {'label': 'LED brand', 'value': 'Bridgelux'}, {'label': 'LED Driver', 'value': 'Inventronics Or Equal'}], help_text='产品能效参数表，用于详情页 ENERGY AND PERFORMANCE DATA 表格。格式：[{"label": "Series Name", "value": "FL4M-320W"}, ...]。label 为参数名称，value 为参数值。不填或留空数组则不显示该行。', verbose_name='Energy & Performance Data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, default='FL1M-80W', help_text='产品型号标识，示例：FL1M-80W-30K-S。新建产品时会自动填充默认值，可按需修改。', max_length=200, verbose_name='Model Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ordering_info',
            field=models.JSONField(blank=True, default=list, help_text='订购信息表格，9 列，每列支持多行（换行分隔）。新建产品时自动填充通用默认值，大部分列（如 CCT、电压、颜色、控制方式、支架等）可直接复用，只需修改 Series Name 和 Power 即可快速完成。', verbose_name='Ordering Information'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL_FIELD', 'Football Field'), ('SOCCER_FIELD', 'Soccer Field'), ('BASEBALL_FIELD', 'Baseball Field'), ('TENNIS_COURTS', 'Tennis Courts'), ('SKI_AREA', 'Ski Area'), ('BASKETBALL', 'Basketball'), ('VELODROME', 'Velodrome'), ('TENNIS', 'Tennis'), ('TRACK_FIELD', 'Track and Field'), ('MULTI_SPORT', 'Multi-Sport Arena'), ('AIRPORT', 'Airport'), ('SEAPORT', 'Seaport'), ('ICE_ARENA', 'Ice Arena'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
