# Generated by Django 6.1 on 2026-08-24 10:40

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_add_product_cert_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='卡片标题，如 "M Series"、"Sports Lighting" 等', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='卡片副标题 / 简短描述，显示在标题下方', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='卡片图片。建议 1280×720 像素（16:9），用于产品列表页卡片展示', upload_to='products_page/')),
                ('link_url', models.CharField(db_index=True, help_text='卡片点击跳转链接，如 "/products/m-series/"', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='显示顺序（数字越小越靠前）')),
                ('is_active', models.BooleanField(default=True, help_text='是否在 Products 页面显示此卡片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Products Page Card',
                'verbose_name_plural': 'Products Page Cards',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_data',
            field=models.JSONField(blank=True, default=pages.models.default_energy_data, help_text='产品能效参数表，用于详情页 ENERGY AND PERFORMANCE DATA 表格。格式：[{"label": "Series Name", "value": "FL4M-320W"}, ...]。label 为参数名称，value 为参数值。不填或留空数组则不显示该行。', verbose_name='Energy & Performance Data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='项目详情页主图。建议 1920×1080 像素（16:9，Retina 屏适配，最小 1280×720）。', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL_FIELD', 'Football Field'), ('SOCCER_FIELD', 'Soccer Field'), ('BASEBALL_FIELD', 'Baseball Field'), ('TENNIS_COURTS', 'Tennis Courts'), ('SKI_AREA', 'Ski Area'), ('KARTING', 'Karting Track'), ('BASKETBALL', 'Basketball'), ('VELODROME', 'Velodrome'), ('TENNIS', 'Tennis & Pickleball'), ('TRACK_FIELD', 'Track and Field'), ('MULTI_SPORT', 'Multi-Sport Arena'), ('FENCING', 'Fencing'), ('AQUATICS_CENTRE', 'Aquatics Centre'), ('AIRPORT', 'Airport'), ('ICE_ARENA', 'Ice Arena'), ('CITY_EXPRESSWAY', 'City Expressway'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='venue_type',
            field=models.CharField(choices=[('OUTDOOR', 'Outdoor'), ('INDOOR', 'Indoor'), ('INFRASTRUCTURE', 'Infrastructure'), ('ROADWAY', 'Roadway')], default='OUTDOOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='项目详情页轮播图。建议 1920×1080 像素（16:9，Retina 屏适配，最小 1280×720）。', upload_to='projects/gallery/'),
        ),
    ]
