# Generated by Django 6.1 on 2026-08-25 06:55

from django.db import migrations, models


def populate_slug_from_link_url(apps, schema_editor):
    ProductsPageCard = apps.get_model('pages', 'ProductsPageCard')
    for card in ProductsPageCard.objects.all():
        if not card.slug and card.link_url:
            card.slug = card.link_url.strip('/').split('/')[-1]
            card.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_productspagecard_alter_product_energy_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspagecard',
            name='slug',
            field=models.CharField(blank=True, db_index=True, help_text='关联的产品 slug，用于匹配卡片与产品。如 "m-series"。修改此字段将改变卡片关联的产品。', max_length=200),
        ),
        migrations.AlterField(
            model_name='productspagecard',
            name='link_url',
            field=models.CharField(db_index=True, help_text='卡片点击跳转链接，如 "/products/m-series/"。仅用于前台跳转，不影响卡片与产品的匹配。', max_length=200),
        ),
        migrations.RunPython(populate_slug_from_link_url, migrations.RunPython.noop),
    ]