# Generated by Django 6.0.7 on 2026-08-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_add_productspagecard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active products appear on the public website.', verbose_name='Active'),
        ),
    ]
