# Generated by Django 6.1 on 2026-09-02 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_add_is_active_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='accent_color',
            field=models.CharField(default='#0088FF', help_text='Primary accent color, e.g. #0088FF, #FF6B00', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS color, e.g. #0088FF or rgb(0, 136, 255).', regex='^(#[0-9A-Fa-f]{3,8}|rgba?\\(\\s*\\d{1,3}\\s*,\\s*\\d{1,3}\\s*,\\s*\\d{1,3}\\s*(,\\s*(0|1|0?\\.\\d+)\\s*)?\\))$')], verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_family_body',
            field=models.CharField(default="'Inter', 'Helvetica Neue', Arial, sans-serif", help_text="CSS font-family value, e.g. 'Inter', sans-serif", max_length=200, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS font-family list, e.g. "\'Inter\', Arial, sans-serif".', regex='^[A-Za-z0-9 \\-.,\'\\"()]+$')], verbose_name='Body Font Family'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_family_heading',
            field=models.CharField(default="'Inter', 'Helvetica Neue', Arial, sans-serif", help_text='CSS font-family value for headings', max_length=200, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS font-family list, e.g. "\'Inter\', Arial, sans-serif".', regex='^[A-Za-z0-9 \\-.,\'\\"()]+$')], verbose_name='Heading Font Family'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_size_base',
            field=models.CharField(default='16px', help_text='Root font size, e.g. 16px, 18px', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS length, e.g. 16px or 1.25rem.', regex='^\\d+(\\.\\d+)?(px|rem|em|ch|vw|vh|%)$')], verbose_name='Base Font Size'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_size_body',
            field=models.CharField(default='1.05rem', help_text='Paragraph text size, e.g. 1.05rem, 1.1rem', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS length, e.g. 16px or 1.25rem.', regex='^\\d+(\\.\\d+)?(px|rem|em|ch|vw|vh|%)$')], verbose_name='Body Text Font Size'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_size_card_desc',
            field=models.CharField(default='0.95rem', help_text='Product/Project card description size', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS length, e.g. 16px or 1.25rem.', regex='^\\d+(\\.\\d+)?(px|rem|em|ch|vw|vh|%)$')], verbose_name='Card Description Font Size'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_size_card_title',
            field=models.CharField(default='1.25rem', help_text='Product/Project card title size', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS length, e.g. 16px or 1.25rem.', regex='^\\d+(\\.\\d+)?(px|rem|em|ch|vw|vh|%)$')], verbose_name='Card Title Font Size'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_size_hero_subtitle',
            field=models.CharField(default='1.15rem', help_text='Hero subtitle size, e.g. 1.15rem, 1.25rem', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS length, e.g. 16px or 1.25rem.', regex='^\\d+(\\.\\d+)?(px|rem|em|ch|vw|vh|%)$')], verbose_name='Hero Subtitle Font Size'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_size_hero_title',
            field=models.CharField(default='3.5rem', help_text='Hero heading size, e.g. 3.5rem, 4rem', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS length, e.g. 16px or 1.25rem.', regex='^\\d+(\\.\\d+)?(px|rem|em|ch|vw|vh|%)$')], verbose_name='Hero Title Font Size'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_size_nav',
            field=models.CharField(default='17px', help_text='Nav link font size, e.g. 15px, 17px, 18px', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS length, e.g. 16px or 1.25rem.', regex='^\\d+(\\.\\d+)?(px|rem|em|ch|vw|vh|%)$')], verbose_name='Navigation Font Size'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_size_section_title',
            field=models.CharField(default='2.25rem', help_text='Section headings size, e.g. 2.25rem, 2.5rem', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS length, e.g. 16px or 1.25rem.', regex='^\\d+(\\.\\d+)?(px|rem|em|ch|vw|vh|%)$')], verbose_name='Section Title Font Size'),
        ),
    ]
