# Generated by Django 6.1 on 2026-09-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_siteconfig_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.CharField(help_text='SHA-256 hash of the visitor IP — plaintext IPs are never stored (#16/GDPR)', max_length=64, verbose_name='IP Address (hashed)'),
        ),
    ]
