# Generated by Django 6.1 on 2026-09-24 01:01

import django.core.validators
from django.db import migrations, models

# v1.6.3 P0-3: SiteConfig 字体栈五处对齐（models 默认 / seed_data.py /
# seed_data.json / base.html critical CSS / base.css → canonical 栈）。
# RunPython 与 0024 同一模式：仅当存量值精确匹配"历史上出现过的默认值"
# 时升级，管理员自定义字体栈原样保留。

CANONICAL = (
    "'Inter', system-ui, -apple-system, BlinkMacSystemFont, "
    "'PingFang SC', 'Hiragino Sans GB', "
    "'Microsoft YaHei', 'Source Han Sans CN', 'Noto Sans CJK SC', "
    "Roboto, sans-serif"
)

OLD_DEFAULTS = (
    # seed 2026-09-17 栈（缺 CJK 兜底）
    "'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, "
    "'Helvetica Neue', Arial, sans-serif",
    # 0024 NEW_DEFAULT / 旧 models 默认（system-ui 顺序不同）
    "'Inter', -apple-system, BlinkMacSystemFont, system-ui, "
    "'PingFang SC', 'Hiragino Sans GB', "
    "'Microsoft YaHei', 'Source Han Sans CN', 'Noto Sans CJK SC', "
    "Roboto, sans-serif",
    # 0024 OLD_DEFAULTS（防御性纳入）
    "'Inter', 'Helvetica Neue', Arial, sans-serif",
    "Inter, 'Helvetica Neue', Arial, sans-serif",
    "'Inter', 'Helvetica Neue', Arial",
    "Inter, Helvetica Neue, Arial, sans-serif",
)


def update_font_stacks(apps, schema_editor):
    SiteConfig = apps.get_model('pages', 'SiteConfig')
    for cfg in SiteConfig.objects.all():
        body_old = cfg.font_family_body in OLD_DEFAULTS
        head_old = cfg.font_family_heading in OLD_DEFAULTS
        if not (body_old or head_old):
            continue  # 管理员自定义值：不碰
        if body_old:
            cfg.font_family_body = CANONICAL
        if head_old:
            cfg.font_family_heading = CANONICAL
        cfg.save(update_fields=[
            f for f, changed in
            (('font_family_body', body_old),
             ('font_family_heading', head_old)) if changed])


def revert_font_stacks(apps, schema_editor):
    """回滚：canonical → seed 2026-09-17 Segoe UI 栈（本迁移前的 seed 值）。"""
    legacy = (
        "'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, "
        "'Helvetica Neue', Arial, sans-serif")
    SiteConfig = apps.get_model('pages', 'SiteConfig')
    for cfg in SiteConfig.objects.all():
        body_new = cfg.font_family_body == CANONICAL
        head_new = cfg.font_family_heading == CANONICAL
        if not (body_new or head_new):
            continue
        if body_new:
            cfg.font_family_body = legacy
        if head_new:
            cfg.font_family_heading = legacy
        cfg.save(update_fields=[
            f for f, changed in
            (('font_family_body', body_new),
             ('font_family_heading', head_new)) if changed])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_add_product_page_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='font_family_body',
            field=models.CharField(default="'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'Source Han Sans CN', 'Noto Sans CJK SC', Roboto, sans-serif", help_text="CSS font-family value, e.g. 'Inter', sans-serif", max_length=200, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS font-family list, e.g. "\'Inter\', Arial, sans-serif".', regex='^[A-Za-z0-9 \\-.,\'\\"()]+$')], verbose_name='Body Font Family'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='font_family_heading',
            field=models.CharField(default="'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'Source Han Sans CN', 'Noto Sans CJK SC', Roboto, sans-serif", help_text='CSS font-family value for headings', max_length=200, validators=[django.core.validators.RegexValidator(message='Enter a valid CSS font-family list, e.g. "\'Inter\', Arial, sans-serif".', regex='^[A-Za-z0-9 \\-.,\'\\"()]+$')], verbose_name='Heading Font Family'),
        ),
        migrations.RunPython(update_font_stacks, revert_font_stacks),
    ]
