# Generated by Django 6.0.7 on 2026-09-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_update_siteconfig_font_stack_p0'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery photo for this article. Rendered at its native size — keep the file around 600 px wide; it will not be cropped.', upload_to='news/')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (px)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.newsarticle', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'News image',
                'verbose_name_plural': 'News images',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
