# Generated by Django 6.0.7 on 2026-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_add_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
