# Generated by Django 6.0.7 on 2026-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_newsarticle_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('Company News', 'Company News'), ('Product News', 'Product News'), ('Case Studies', 'Case Studies')], default='Company News', max_length=50),
        ),
    ]
