# Generated by Django 6.0.7 on 2026-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_add_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='energy_data',
            field=models.JSONField(blank=True, default=list, help_text='产品能效参数表，用于详情页 ENERGY AND PERFORMANCE DATA 表格。格式：[{"label": "Series Name", "value": "FL4M-320W"}, ...]。label 为参数名称，value 为参数值。不填或留空数组则不显示该行。', verbose_name='Energy & Performance Data'),
        ),
    ]
