# Generated by Django 6.0.7 on 2026-10-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_alter_product_energy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='从已上传的轮播图里选一张作为封面/卡片主图。选中后前端直接复用该轮播图文件，不额外占用空间；留空则使用上方「主图」字段。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_product', to='pages.productimage', verbose_name='封面图（从轮播图选择）'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='从已上传的轮播图里选一张作为封面/卡片主图。选中后前端直接复用该轮播图文件，不额外占用空间；留空则使用上方「主图」字段，主图也空时自动取第一张轮播图。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_project', to='pages.projectimage', verbose_name='封面图（从轮播图选择）'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('Exhibition Information', 'Exhibition Information'), ('Product News', 'Product News'), ('Case Studies', 'Case Studies'), ('Industry Insights', 'Industry Insights')], default='Exhibition Information', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='产品卡片/详情主图（独立上传）。若已在下方「Product images」中选了某张轮播图当封面，这里留空即可，避免重复保存同一张图。', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='项目详情页主图（独立上传）。若已在下方「Project images」中选了某张轮播图当封面，这里留空即可，避免重复保存同一张图。', upload_to='projects/'),
        ),
    ]
