# Generated by Django 6.0.7 on 2026-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_add_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text='产品型号标识，示例：FL1M-80W-30K-S。必须与本产品的实际型号一致 —— 它会直接进入 <title> 与 meta description（SEO 公式见 pages/utils.py），填错等于给别的产品代打广告。', max_length=200, verbose_name='Model Number'),
        ),
    ]
