# Generated by Django 6.0.7 on 2026-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_product_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Pick the luminaires this project actually used. Leave it empty to hide the "Related Products" section entirely.', related_name='related_projects', to='pages.product', verbose_name='Related Products'),
        ),
    ]
