# Generated by Django 6.0.7 on 2026-10-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_project_related_products_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application_cases',
            field=models.ManyToManyField(blank=True, help_text='Manually pick the projects to display in the product detail page "Application Cases" section. Leave empty to hide the entire section.', related_name='product_application_cases', to='pages.project', verbose_name='Application Cases'),
        ),
    ]
