"""Responsive image template tags (SEO/GEO batch C, v1.10.18).

Usage in templates (after ``{% load image_tags %}``)::

    <img src="{{ product.image_url|src:720 }}"
         srcset="{{ product.image_url|srcset }}"
         sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw, 33vw"
         loading="lazy" decoding="async" alt="...">

``srcset`` emits ``<url> 360w, <url> 720w, <url> 1248w`` for the canonical
responsive variants generated by ``scripts/gen_image_variants.py``. ``src:<w>``
returns a single variant URL (default 720) for the non-srcset fallback.

Both rely on ``pages.image_variants`` which reverses the (possibly content-hashed)
``image_url`` to a canonical static path, derives the mirrored ``_variants``
relative path, and resolves it through Django's ``static()`` — so the URLs are
correct in both dev (unhashed) and production (hashed manifest).
"""
from django import template

from pages.image_variants import build_src, build_srcset

register = template.Library()


@register.filter
def srcset(url):
    """Return a ``srcset`` attribute *value* (no ``srcset=``) for a static image URL.

    Empty input yields '' so the attribute can be rendered harmlessly.
    """
    return build_srcset(url)


@register.filter
def src(url, width=720):
    """Return a single responsive ``src`` URL for a static image URL.

    ``width`` selects the variant (default 720). ``{{ x|src:1248 }}`` for a hero.
    """
    try:
        width = int(width)
    except (TypeError, ValueError):
        width = 720
    return build_src(url, width)
